"""Tungsten RGB 1D look — identity abscissa, locked channel gains.

Gains (Captain / Phase A lock): R 1.18, G 1.00, B 0.78.
Abscissa is identity (not the WS2816 inverse-gamma). 256 u16 nodes per
channel, strictly monotone, endpoints 0 and 65535.

Used as:
- generator for SPECTRASYNQ_K1_FIRMWARE/visual/k1_look_tungsten.h
- host replica for tests/test_look_apply.py
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Sequence, Tuple

N = 256
MAX_U16 = 65535
GAIN_R = 1.18
GAIN_G = 1.00
GAIN_B = 0.78

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "SPECTRASYNQ_K1_FIRMWARE" / "visual" / "k1_look_tungsten.h"


def nodes_x() -> List[int]:
    xs = [int(round((k / 255.0) * MAX_U16)) for k in range(N)]
    xs[0] = 0
    xs[-1] = MAX_U16
    for i in range(1, N):
        if xs[i] <= xs[i - 1]:
            xs[i] = xs[i - 1] + 1
    if xs[-1] != MAX_U16:
        raise ValueError("tungsten x[255] is not 65535")
    if any(xs[i] <= xs[i - 1] for i in range(1, N)):
        raise ValueError("tungsten x is not strictly increasing")
    return xs


def _channel(xs: Sequence[int], gain: float) -> List[int]:
    ys = [int(round(x * gain)) for x in xs]
    ys = [0 if y < 0 else MAX_U16 if y > MAX_U16 else y for y in ys]
    ys[0] = 0
    ys[-1] = MAX_U16
    for i in range(1, N):
        if ys[i] < ys[i - 1]:
            ys[i] = ys[i - 1]
    ys[-1] = MAX_U16
    return ys


def nodes_rgb(xs: Sequence[int] | None = None) -> Tuple[List[int], List[int], List[int]]:
    if xs is None:
        xs = nodes_x()
    return _channel(xs, GAIN_R), _channel(xs, GAIN_G), _channel(xs, GAIN_B)


def apply_u16(
    v: int,
    xs: Sequence[int] | None = None,
    ys: Sequence[int] | None = None,
) -> int:
    if xs is None:
        xs = nodes_x()
    if ys is None:
        ys = _channel(xs, GAIN_G)
    if v <= 0:
        return 0
    if v >= MAX_U16:
        return MAX_U16
    lo, hi = 0, N - 1
    while hi - lo > 1:
        mid = (lo + hi) >> 1
        if xs[mid] <= v:
            lo = mid
        else:
            hi = mid
    x0, x1 = xs[lo], xs[hi]
    y0, y1 = ys[lo], ys[hi]
    if x1 <= x0:
        return y0
    num = (y1 - y0) * (v - x0)
    den = x1 - x0
    return y0 + (num + (den // 2)) // den


def apply_rgb(r: int, g: int, b: int) -> Tuple[int, int, int]:
    xs = nodes_x()
    yr, yg, yb = nodes_rgb(xs)
    return apply_u16(r, xs, yr), apply_u16(g, xs, yg), apply_u16(b, xs, yb)


def _fmt_array(name: str, values: Sequence[int]) -> str:
    lines = [f"inline constexpr uint16_t {name}[256] = {{"]
    row: List[str] = []
    for i, v in enumerate(values):
        row.append(f"0x{v:04x}")
        if len(row) == 12 or i == len(values) - 1:
            comma = "," if i != len(values) - 1 else ""
            lines.append("    " + ", ".join(row) + comma)
            row = []
    lines.append("};")
    return "\n".join(lines)


def generate_header(path: Path | None = None) -> str:
    xs = nodes_x()
    yr, yg, yb = nodes_rgb(xs)
    body = "\n".join(
        [
            "#pragma once",
            "",
            "#include <stdint.h>",
            "",
            "// Generated by tests/look_tungsten_lut.py — do not hand-edit.",
            "// Tungsten RGB 1D (identity abscissa). Gains R 1.18 / G 1.00 / B 0.78.",
            "// Endpoints 0 and 65535. Strictly monotone per channel.",
            "",
            _fmt_array("k1_look_tungsten_x", xs),
            "",
            _fmt_array("k1_look_tungsten_r", yr),
            "",
            _fmt_array("k1_look_tungsten_g", yg),
            "",
            _fmt_array("k1_look_tungsten_b", yb),
            "",
        ]
    )
    out = path or HEADER
    out.write_text(body + "\n", encoding="utf-8")
    return body


if __name__ == "__main__":
    generate_header()
    print(f"wrote {HEADER}")
