#pragma once
/* Auto-generated by tools/deck_ui_assets.py — do not edit.
 * Modes  : SPECTRASYNQ_K1_FIRMWARE/system/system.h set_mode_name()
 * Enabled: SPECTRASYNQ_K1_FIRMWARE/system/config_types.h light_mode_is_enabled()
 * Palettes: SPECTRASYNQ_K1_FIRMWARE/visual/Palettes.h paletteNames[]
 * Display names = mechanical transform of firmware identifiers (no invented synonyms).
 */

#include <stdint.h>
#include <stdbool.h>

#define DECK_MODE_COUNT              33
#define DECK_MODE_COUNT_CURATED      DECK_MODE_COUNT  /* legacy alias */
#define DECK_PALETTE_COUNT           44

static const char* const kDeckModeNames[DECK_MODE_COUNT] = {
  "GDFT",  /* 00 */
  "CHROMAGRAM",  /* 01 */
  "CHROMAGRAM DOTS",  /* 02 */
  "BLOOM",  /* 03 */
  "VU DOT",  /* 04 */
  "KALEIDOSCOPE",  /* 05 */
  "QUANTUM COLLAPSE",  /* 06 */
  "WAVEFORM-FAST",  /* 07 */
  "WAVEFORM",  /* 08 */
  "BLOOM (FAST)",  /* 09 */
  "VU",  /* 10 */
  "WAVEFORM_HYBRID",  /* 11 */
  "AURORA",  /* 12 */
  "COMET",  /* 13 */
  "SPECTRUM RIVER",  /* 14 */
  "SPECTRUM RIVER 2",  /* 15 */
  "EMBER FIELD",  /* 16 */
  "EMBER FIELD 2",  /* 17 */
  "WAVEFORM TEMPO",  /* 18 */
  "TEMPO RIVER",  /* 19 */
  "TEMPO COMET",  /* 20 */
  "DENSE FORGE",  /* 21 */
  "SNAPWAVE",  /* 22 */
  "PULSE PRISM",  /* 23 */
  "DENSE FORGE CHORD",  /* 24 */
  "CHROMA CONSTELLATION",  /* 25 */
  "PERCUSSION BURST",  /* 26 */
  "TEMPO COMET ANTICIPATE",  /* 27 */
  "RIVER SURGE",  /* 28 */
  "TEMPO RIVER WALK",  /* 29 */
  "BEAT PULSE",  /* 30 */
  "BLOOM BASSTREBLE",  /* 31 */
  "WAVEFORM HYBRID K1",  /* 32 */
};

/* 1 = selectable (mirrors light_mode_is_enabled). */
static const uint8_t kDeckModeEnabled[DECK_MODE_COUNT] = {
  0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
  1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
};

/* Firmware paletteNames[] identifiers (source of truth). */
static const char* const kDeckPaletteIdents[DECK_PALETTE_COUNT] = {
  "Sunset_Real_gp",  /* 00 */
  "es_rivendell_15_gp",  /* 01 */
  "es_ocean_breeze_036_gp",  /* 02 */
  "rgi_15_gp",  /* 03 */
  "retro2_16_gp",  /* 04 */
  "Analogous_1_gp",  /* 05 */
  "es_pinksplash_08_gp",  /* 06 */
  "Coral_reef_gp",  /* 07 */
  "es_ocean_breeze_068_gp",  /* 08 */
  "es_pinksplash_07_gp",  /* 09 */
  "es_vintage_01_gp",  /* 10 */
  "departure_gp",  /* 11 */
  "es_landscape_64_gp",  /* 12 */
  "es_landscape_33_gp",  /* 13 */
  "rainbowsherbet_gp",  /* 14 */
  "gr65_hult_gp",  /* 15 */
  "gr64_hult_gp",  /* 16 */
  "GMT_drywet_gp",  /* 17 */
  "ib_jul01_gp",  /* 18 */
  "es_vintage_57_gp",  /* 19 */
  "ib15_gp",  /* 20 */
  "Fuschia_7_gp",  /* 21 */
  "es_emerald_dragon_08_gp",  /* 22 */
  "lava_gp",  /* 23 */
  "fire_gp",  /* 24 */
  "Colorfull_gp",  /* 25 */
  "Magenta_Evening_gp",  /* 26 */
  "Pink_Purple_gp",  /* 27 */
  "es_autumn_19_gp",  /* 28 */
  "BlacK_Blue_Magenta_White_gp",  /* 29 */
  "BlacK_Magenta_Red_gp",  /* 30 */
  "BlacK_Red_Magenta_Yellow_gp",  /* 31 */
  "Blue_Cyan_Yellow_gp",  /* 32 */
  "K1_Iris_Apricot_gp",  /* 33 */
  "K1_Tropical_Ultraviolet_gp",  /* 34 */
  "K1_Chameleon_Flare_gp",  /* 35 */
  "K1_Coral_Sunset_gp",  /* 36 */
  "K1_Night_Sea_Amber_gp",  /* 37 */
  "K1_Crimson_Gold_gp",  /* 38 */
  "K1_Ultraviolet_Ascend_gp",  /* 39 */
  "K1_Naberius_Gold_gp",  /* 40 */
  "K1_Vepar_Pink_gp",  /* 41 */
  "K1_Flourish_Sweep_gp",  /* 42 */
  "K1_Ultraviolet_Bright_gp",  /* 43 */
};

/* UI display strings derived from identifiers (strip _gp/K1_, UPPER). */
static const char* const kDeckPaletteNames[DECK_PALETTE_COUNT] = {
  "SUNSET REAL",  /* 00 ← Sunset_Real_gp */
  "ES RIVENDELL 15",  /* 01 ← es_rivendell_15_gp */
  "ES OCEAN BREEZE 036",  /* 02 ← es_ocean_breeze_036_gp */
  "RGI 15",  /* 03 ← rgi_15_gp */
  "RETRO2 16",  /* 04 ← retro2_16_gp */
  "ANALOGOUS 1",  /* 05 ← Analogous_1_gp */
  "ES PINKSPLASH 08",  /* 06 ← es_pinksplash_08_gp */
  "CORAL REEF",  /* 07 ← Coral_reef_gp */
  "ES OCEAN BREEZE 068",  /* 08 ← es_ocean_breeze_068_gp */
  "ES PINKSPLASH 07",  /* 09 ← es_pinksplash_07_gp */
  "ES VINTAGE 01",  /* 10 ← es_vintage_01_gp */
  "DEPARTURE",  /* 11 ← departure_gp */
  "ES LANDSCAPE 64",  /* 12 ← es_landscape_64_gp */
  "ES LANDSCAPE 33",  /* 13 ← es_landscape_33_gp */
  "RAINBOWSHERBET",  /* 14 ← rainbowsherbet_gp */
  "GR65 HULT",  /* 15 ← gr65_hult_gp */
  "GR64 HULT",  /* 16 ← gr64_hult_gp */
  "GMT DRYWET",  /* 17 ← GMT_drywet_gp */
  "IB JUL01",  /* 18 ← ib_jul01_gp */
  "ES VINTAGE 57",  /* 19 ← es_vintage_57_gp */
  "IB15",  /* 20 ← ib15_gp */
  "FUSCHIA 7",  /* 21 ← Fuschia_7_gp */
  "ES EMERALD DRAGON 08",  /* 22 ← es_emerald_dragon_08_gp */
  "LAVA",  /* 23 ← lava_gp */
  "FIRE",  /* 24 ← fire_gp */
  "COLORFULL",  /* 25 ← Colorfull_gp */
  "MAGENTA EVENING",  /* 26 ← Magenta_Evening_gp */
  "PINK PURPLE",  /* 27 ← Pink_Purple_gp */
  "ES AUTUMN 19",  /* 28 ← es_autumn_19_gp */
  "BLACK BLUE MAGENTA WHITE",  /* 29 ← BlacK_Blue_Magenta_White_gp */
  "BLACK MAGENTA RED",  /* 30 ← BlacK_Magenta_Red_gp */
  "BLACK RED MAGENTA YELLOW",  /* 31 ← BlacK_Red_Magenta_Yellow_gp */
  "BLUE CYAN YELLOW",  /* 32 ← Blue_Cyan_Yellow_gp */
  "IRIS APRICOT",  /* 33 ← K1_Iris_Apricot_gp */
  "TROPICAL ULTRAVIOLET",  /* 34 ← K1_Tropical_Ultraviolet_gp */
  "CHAMELEON FLARE",  /* 35 ← K1_Chameleon_Flare_gp */
  "CORAL SUNSET",  /* 36 ← K1_Coral_Sunset_gp */
  "NIGHT SEA AMBER",  /* 37 ← K1_Night_Sea_Amber_gp */
  "CRIMSON GOLD",  /* 38 ← K1_Crimson_Gold_gp */
  "ULTRAVIOLET ASCEND",  /* 39 ← K1_Ultraviolet_Ascend_gp */
  "NABERIUS GOLD",  /* 40 ← K1_Naberius_Gold_gp */
  "VEPAR PINK",  /* 41 ← K1_Vepar_Pink_gp */
  "FLOURISH SWEEP",  /* 42 ← K1_Flourish_Sweep_gp */
  "ULTRAVIOLET BRIGHT",  /* 43 ← K1_Ultraviolet_Bright_gp */
};

static inline const char* deck_mode_name(uint8_t index)
{
  if (index < DECK_MODE_COUNT) return kDeckModeNames[index];
  return "MODE";
}

static inline bool deck_mode_is_enabled(uint8_t index)
{
  if (index >= DECK_MODE_COUNT) return false;
  return kDeckModeEnabled[index] != 0;
}

static inline const char* deck_palette_name(uint8_t index)
{
  if (index < DECK_PALETTE_COUNT) return kDeckPaletteNames[index];
  return "PALETTE";
}

static inline const char* deck_palette_ident(uint8_t index)
{
  if (index < DECK_PALETTE_COUNT) return kDeckPaletteIdents[index];
  return "";
}

