// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 SpectraSynq
// AUTO-GENERATED by scripts/ble_midi/gen_k1_ble_midi_header.py -- DO NOT EDIT.
// Source map: k1-ble-midi-map.json (registry 2026-06-09, md5 78fb9af986da36922fae33cb09de3b4b)
// The knob's BLE-MIDI emission is generated from the K1's committed control map,
// so it cannot drift from the 71-path / 22-mode K1 control surface.
#pragma once
#include <stdint.h>
#include <math.h>

#define K1_BLE_MIDI_CONTROL_COUNT 71
#define K1_BLE_MIDI_TEXT_VALUE_COUNT 21
#define K1_BLE_MIDI_REGISTRY_MD5 "78fb9af986da36922fae33cb09de3b4b"

typedef enum {
  K1MIDI_PC = 0,    // mode select   -> Program Change
  K1MIDI_CC14,      // ranged float  -> 14-bit CC pair (msb, lsb=msb+32)
  K1MIDI_CC7_BOOL,  // toggle        -> 7-bit CC (0/127)
  K1MIDI_CC7_ENUM,  // index/enum    -> 7-bit CC (index)
  K1MIDI_NRPN,      // text/command  -> NRPN (param, data)
} K1MidiType;

typedef enum {
  K1MIDI_FLAG_COMMAND = 1 << 0,
  K1MIDI_FLAG_PROTECTED_APPLY = 1 << 1,
} K1MidiFlags;

typedef struct {
  const char* path;
  uint8_t  channel;     // MIDI channel 0..15
  uint8_t  type;        // K1MidiType
  uint8_t  cc_msb;      // cc14: MSB controller; cc7: the controller; else 0
  uint8_t  cc_lsb;      // cc14: LSB controller (=msb+32); else 0
  uint16_t nrpn_param;  // nrpn: parameter number; else 0
  float    vmin, vmax;  // float range; else 0
  uint8_t  text_index;  // first index in kK1BleMidiTextValues
  uint8_t  text_count;  // number of exact text values for NRPN controls
  uint8_t  flags;       // K1MidiFlags
} K1BleMidiEntry;

static const K1BleMidiEntry kK1BleMidiMap[K1_BLE_MIDI_CONTROL_COUNT] = {
  { "primary.mode", 0, K1MIDI_PC, 0, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.palette", 0, K1MIDI_CC7_ENUM, 102, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.palette_mode", 0, K1MIDI_CC7_BOOL, 64, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.photons", 0, K1MIDI_CC14, 1, 33, 0, 0.05f, 1.0f, 0, 0, 0 },
  { "primary.chroma", 0, K1MIDI_CC14, 2, 34, 0, 0.0f, 1.0f, 0, 0, 0 },
  { "primary.mood", 0, K1MIDI_CC14, 3, 35, 0, 0.0f, 1.0f, 0, 0, 0 },
  { "primary.saturation", 0, K1MIDI_CC14, 4, 36, 0, 0.0f, 1.0f, 0, 0, 0 },
  { "primary.square_iter", 0, K1MIDI_CC14, 5, 37, 0, 0.0f, 8.0f, 0, 0, 0 },
  { "primary.mirror", 0, K1MIDI_CC7_BOOL, 65, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.auto_color_shift", 0, K1MIDI_CC7_BOOL, 66, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.reverse_order", 0, K1MIDI_CC7_BOOL, 67, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.incandescent_mode", 0, K1MIDI_CC7_BOOL, 68, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.incandescent_filter", 0, K1MIDI_CC14, 7, 39, 0, 0.0f, 1.0f, 0, 0, 0 },
  { "primary.bulb_opacity", 0, K1MIDI_CC14, 8, 40, 0, 0.0f, 1.0f, 0, 0, 0 },
  { "primary.base_coat", 0, K1MIDI_CC7_BOOL, 69, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.base_coat_intensity", 0, K1MIDI_CC14, 9, 41, 0, 0.0f, 1.0f, 0, 0, 0 },
  { "primary.temporal_dithering", 0, K1MIDI_CC7_BOOL, 70, 0, 0, 0.0f, 0.0f, 0, 0, 0 },
  { "primary.prism_count", 0, K1MIDI_CC14, 10, 42, 0, 0.0f, 8.0f, 0, 0, 0 },
  { "primary.preset", 0, K1MIDI_NRPN, 0, 0, 0, 0.0f, 0.0f, 0, 5, 0 },
  { "secondary.mode", 1, K1MIDI_PC, 0, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.palette", 1, K1MIDI_CC7_ENUM, 102, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.palette_mode", 1, K1MIDI_CC7_BOOL, 64, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.enabled", 1, K1MIDI_CC7_BOOL, 65, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.photons", 1, K1MIDI_CC14, 1, 33, 0, 0.05f, 1.0f, 5, 0, 0 },
  { "secondary.chroma", 1, K1MIDI_CC14, 2, 34, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "secondary.mood", 1, K1MIDI_CC14, 3, 35, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "secondary.saturation", 1, K1MIDI_CC14, 4, 36, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "secondary.mirror", 1, K1MIDI_CC7_BOOL, 66, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.incandescent_mode", 1, K1MIDI_CC7_BOOL, 67, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.incandescent_filter", 1, K1MIDI_CC14, 5, 37, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "secondary.base_coat", 1, K1MIDI_CC7_BOOL, 68, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.base_coat_intensity", 1, K1MIDI_CC14, 7, 39, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "secondary.auto_color_shift", 1, K1MIDI_CC7_BOOL, 69, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "secondary.reverse_order", 1, K1MIDI_CC7_BOOL, 70, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "global.sensitivity", 2, K1MIDI_CC14, 1, 33, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "global.standby_dimming", 2, K1MIDI_CC7_BOOL, 64, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "global.chroma_profile", 2, K1MIDI_CC7_ENUM, 102, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "global.chromagram_range", 2, K1MIDI_CC14, 2, 34, 0, 1.0f, 80.0f, 5, 0, 0 },
  { "global.max_current_ma", 2, K1MIDI_CC14, 3, 35, 0, 100.0f, 5000.0f, 5, 0, 0 },
  { "global.master_brightness", 2, K1MIDI_CC14, 4, 36, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "director.enabled", 3, K1MIDI_CC7_BOOL, 64, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "director.assist", 3, K1MIDI_CC7_BOOL, 65, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "director.autonomy", 3, K1MIDI_CC7_BOOL, 66, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "director.confidence_floor", 3, K1MIDI_CC14, 1, 33, 0, 0.0f, 1.0f, 5, 0, 0 },
  { "hooks.enabled", 3, K1MIDI_CC7_BOOL, 67, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "edge.enabled", 4, K1MIDI_CC7_BOOL, 64, 0, 0, 0.0f, 0.0f, 5, 0, 0 },
  { "edge.mode", 4, K1MIDI_NRPN, 0, 0, 0, 0.0f, 0.0f, 5, 7, 0 },
  { "edge.strength", 4, K1MIDI_CC14, 1, 33, 0, 0.0f, 1.0f, 12, 0, 0 },
  { "scene.smart", 4, K1MIDI_NRPN, 0, 0, 1, 0.0f, 0.0f, 12, 4, 0 },
  { "vp.profile", 5, K1MIDI_NRPN, 0, 0, 0, 0.0f, 0.0f, 16, 4, 0 },
  { "vp.fix.agc_soft_knee", 5, K1MIDI_CC7_BOOL, 64, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.fix.chroma_gate", 5, K1MIDI_CC7_BOOL, 65, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.fix.prism_off", 5, K1MIDI_CC7_BOOL, 66, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.fix.bloom_decay", 5, K1MIDI_CC7_BOOL, 67, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.fix.hsv_source_sat", 5, K1MIDI_CC7_BOOL, 68, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.fix.secondary_clean", 5, K1MIDI_CC7_BOOL, 69, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.bloom.alpha", 5, K1MIDI_CC14, 1, 33, 0, 0.8f, 1.0f, 20, 0, 0 },
  { "vp.bloom.shift_scale", 5, K1MIDI_CC14, 2, 34, 0, 0.25f, 2.0f, 20, 0, 0 },
  { "vp.bloom.force_saturation", 5, K1MIDI_CC7_BOOL, 70, 0, 0, 0.0f, 0.0f, 20, 0, 0 },
  { "vp.waveform.shift_rate", 5, K1MIDI_CC14, 3, 35, 0, 0.0f, 240.0f, 20, 0, 0 },
  { "vp.waveform.idle_fade", 5, K1MIDI_CC14, 4, 36, 0, 0.5f, 0.999f, 20, 0, 0 },
  { "vp.waveform.raw_margin", 5, K1MIDI_CC14, 5, 37, 0, 1.0f, 3.0f, 20, 0, 0 },
  { "vp.waveform.peak_floor", 5, K1MIDI_CC14, 7, 39, 0, 0.0f, 1.0f, 20, 0, 0 },
  { "vp.waveform.active_fade", 5, K1MIDI_CC14, 8, 40, 0, 0.0f, 0.5f, 20, 0, 0 },
  { "vp.waveform.chroma_blend_gain", 5, K1MIDI_CC14, 9, 41, 0, 0.0f, 4.0f, 20, 0, 0 },
  { "vp.waveform.fallback_brightness", 5, K1MIDI_CC14, 10, 42, 0, 0.0f, 1.0f, 20, 0, 0 },
  { "vp.waveform.vu_floor", 5, K1MIDI_CC14, 11, 43, 0, 0.0f, 1.0f, 20, 0, 0 },
  { "calibration.noise.arm", 6, K1MIDI_NRPN, 0, 0, 0, 0.0f, 0.0f, 20, 0, K1MIDI_FLAG_COMMAND | K1MIDI_FLAG_PROTECTED_APPLY },
  { "calibration.noise.confirm", 6, K1MIDI_NRPN, 0, 0, 1, 0.0f, 0.0f, 20, 0, K1MIDI_FLAG_COMMAND | K1MIDI_FLAG_PROTECTED_APPLY },
  { "calibration.noise.status", 6, K1MIDI_NRPN, 0, 0, 2, 0.0f, 0.0f, 20, 0, K1MIDI_FLAG_COMMAND | K1MIDI_FLAG_PROTECTED_APPLY },
  { "calibration.noise.clear", 6, K1MIDI_NRPN, 0, 0, 3, 0.0f, 0.0f, 20, 1, K1MIDI_FLAG_PROTECTED_APPLY },
};

static const char* const kK1BleMidiTextValues[K1_BLE_MIDI_TEXT_VALUE_COUNT] = {
  "default",
  "tinted_bulbs",
  "incandescent",
  "white",
  "classic",
  "off",
  "analogous",
  "complementary",
  "split",
  "veil",
  "triadic",
  "tetradic",
  "off",
  "assist",
  "l1",
  "auto",
  "original",
  "clean",
  "candidate",
  "custom",
  "CONFIRM",
};

// Encode one logical control change into a MIDI 1.0 byte stream (status+data,
// running status NOT used). Returns the number of bytes written to `out`
// (out must hold >= 12). Rounding is round-half-up to match the host parity
// reference; the K1 decoder dequantises, so the rounding choice only moves a
// float by <=1 LSB of the 14-bit grid (within the documented tolerance).
static inline int k1_ble_midi_encode(const K1BleMidiEntry* e, float value, uint8_t* out) {
  uint8_t ch = (uint8_t)(e->channel & 0x0F);
  switch (e->type) {
    case K1MIDI_CC14: {
      float t = (e->vmax > e->vmin) ? (value - e->vmin) / (e->vmax - e->vmin) : 0.0f;
      int n = (int)floorf(t * 16383.0f + 0.5f);
      if (n < 0) n = 0;
      if (n > 16383) n = 16383;
      out[0] = (uint8_t)(0xB0 | ch); out[1] = e->cc_msb; out[2] = (uint8_t)((n >> 7) & 0x7F);
      out[3] = (uint8_t)(0xB0 | ch); out[4] = e->cc_lsb; out[5] = (uint8_t)(n & 0x7F);
      return 6;
    }
    case K1MIDI_CC7_BOOL:
      out[0] = (uint8_t)(0xB0 | ch); out[1] = e->cc_msb; out[2] = (value != 0.0f) ? 127 : 0;
      return 3;
    case K1MIDI_CC7_ENUM:
      out[0] = (uint8_t)(0xB0 | ch); out[1] = e->cc_msb; out[2] = (uint8_t)((int)value & 0x7F);
      return 3;
    case K1MIDI_PC:
      out[0] = (uint8_t)(0xC0 | ch); out[1] = (uint8_t)((int)value & 0x7F);
      return 2;
    case K1MIDI_NRPN: {
      int d = (int)value & 0x3FFF;
      uint16_t p = e->nrpn_param;
      out[0]  = (uint8_t)(0xB0 | ch); out[1]  = 99; out[2]  = (uint8_t)((p >> 7) & 0x7F);
      out[3]  = (uint8_t)(0xB0 | ch); out[4]  = 98; out[5]  = (uint8_t)(p & 0x7F);
      out[6]  = (uint8_t)(0xB0 | ch); out[7]  = 6;  out[8]  = (uint8_t)((d >> 7) & 0x7F);
      out[9]  = (uint8_t)(0xB0 | ch); out[10] = 38; out[11] = (uint8_t)(d & 0x7F);
      return 12;
    }
  }
  return 0;
}
