#!/usr/bin/env python3
"""Generate Tab5 K1ControlRegistry.h from docs/protocol/k1-ws-controls-registry.yaml."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_YAML = ROOT / "docs/protocol/k1-ws-controls-registry.yaml"
DEFAULT_OUT = ROOT / "sb-tab5-wireless-controller/src/network/K1ControlRegistry.h"


def infer_tier(path: str) -> str:
    if path.startswith("calibration."):
        return "c1"
    if path.startswith("vp."):
        return "p2"
    return "p1"


def render(registry_id: str, controls: list[str]) -> str:
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Copyright 2025-2026 SpectraSynq",
        "#pragma once",
        "",
        "// AUTO-GENERATED by scripts/regression-harness/k1_ws_registry_codegen.py",
        "// Source: docs/protocol/k1-ws-controls-registry.yaml",
        "",
        '#include <cstring>',
        "",
        f'#define K1_CONTROL_REGISTRY_ID "{registry_id}"',
        f"#define K1_CONTROL_REGISTRY_COUNT {len(controls)}",
        "",
        "static constexpr const char* kK1ControlPaths[] = {",
    ]
    for path in controls:
        lines.append(f'    "{path}",')
    lines.extend(
        [
            "    nullptr,",
            "};",
            "",
            "inline const char* k1ControlTierForPath(const char* path) {",
            '    if (path == nullptr || path[0] == \'\\0\') {',
            '        return "";',
            "    }",
            '    if (strncmp(path, "calibration.", 12) == 0) {',
            '        return "c1";',
            "    }",
            '    if (strncmp(path, "vp.", 3) == 0) {',
            '        return "p2";',
            "    }",
            '    return "p1";',
            "}",
            "",
            "inline bool k1ControlPathKnown(const char* path) {",
            "    if (path == nullptr) {",
            "        return false;",
            "    }",
            "    for (const char* const* entry = kK1ControlPaths; *entry != nullptr; ++entry) {",
            "        if (strcmp(path, *entry) == 0) {",
            "            return true;",
            "        }",
            "    }",
            "    return false;",
            "}",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--yaml", type=Path, default=DEFAULT_YAML)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    data = yaml.safe_load(args.yaml.read_text(encoding="utf-8"))
    registry_id = str(data.get("version", ""))
    controls = [str(item) for item in data.get("controls", [])]
    if not registry_id or not controls:
        raise SystemExit("registry yaml missing version or controls")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(registry_id, controls), encoding="utf-8")
    print(f"wrote {args.out} ({len(controls)} controls, registry={registry_id})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
