#!/usr/bin/env python3
"""Generate the runtime tunable registry from system/globals.h.

Captain's directive (2026-08-14): every AP and VP parameter must be retunable at
runtime. Hand-writing ~170 serial handlers is unmaintainable and drifts silently, so
the registry is GENERATED from the declarations and pinned by a test that regenerates
and diffs — if someone adds a parameter and forgets the registry, CI goes red.

Parameter vs state is decided MECHANICALLY, not by naming taste: a tunable is a
declaration that is never ASSIGNED anywhere outside globals.h. Anything the pipeline
writes each frame (counters, FPS, latched flags) is state and must not be writable, or
a "tune" would be silently overwritten a millisecond later — an indicator wired to
nothing, which is the failure class this repo keeps paying for.

Usage:
  python3 scripts/tools/gen_tunables.py            # write the header
  python3 scripts/tools/gen_tunables.py --check    # exit 1 if out of date
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GLOBALS = ROOT / "SPECTRASYNQ_K1_FIRMWARE" / "system" / "globals.h"
OUT = ROOT / "SPECTRASYNQ_K1_FIRMWARE" / "system" / "k1_tunables_generated.h"
SRC = ROOT / "SPECTRASYNQ_K1_FIRMWARE"

# Only AP/VP parameter namespaces. Deliberately NOT every global in the file.
# All UPPER_SNAKE inline scalars are parameters by this codebase's convention.
# The hot-path rule below does the real filtering; the name shape only keeps
# lower-case working variables out.
NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")

DECL_RE = re.compile(
    r"^inline\s+(float|uint32_t|uint16_t|uint8_t|int8_t|int16_t|int32_t|int|bool)\s+"
    r"([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+);(?:\s*//\s*(.*))?$")

CTYPE = {
    "float": "K1_TUNE_F32", "bool": "K1_TUNE_BOOL",
    "uint32_t": "K1_TUNE_U32", "uint16_t": "K1_TUNE_U16", "uint8_t": "K1_TUNE_U8",
    "int8_t": "K1_TUNE_I32", "int16_t": "K1_TUNE_I32",
    "int32_t": "K1_TUNE_I32", "int": "K1_TUNE_I32",
}


# Per-frame pipeline directories. An assignment HERE means the value is recomputed
# during normal operation, so exposing a setter would be a control that does nothing.
# Assignments from control/, serial/, persistence/ and calibration/ are the existing
# TUNING and restore paths — they do not make a parameter into state.
HOT_PATH = ("/audio/", "/visual/", "/effects/", "/director/", "/diag/")


def assigned_in_hot_path(name):
    """True if the per-frame pipeline writes this symbol => STATE, not a tunable."""
    try:
        out = subprocess.run(
            ["grep", "-rnE",
             rf"(^|[^A-Za-z0-9_]){re.escape(name)}\s*(=[^=]|\+=|-=|\*=|/=|\+\+|--)",
             str(SRC)],
            capture_output=True, text=True).stdout
    except Exception:
        return True  # fail closed: unknown => never expose a writer
    for line in out.splitlines():
        path = line.split(":", 1)[0]
        if any(seg in path for seg in HOT_PATH):
            return True
    return False


def collect():
    out, skipped = [], []
    for raw in GLOBALS.read_text(encoding="utf-8").splitlines():
        m = DECL_RE.match(raw.strip())
        if not m:
            continue
        ctype, name, _default, comment = m.groups()
        if not NAME_RE.match(name):
            continue
        if assigned_in_hot_path(name):
            skipped.append(name)
            continue
        doc = (comment or "").strip().replace('"', "'")
        if len(doc) > 88:
            doc = doc[:85] + "..."
        out.append((name, CTYPE[ctype], doc))
    out.sort(key=lambda r: r[0])
    return out, sorted(skipped)


def render(rows):
    lines = [
        "// GENERATED by scripts/tools/gen_tunables.py — DO NOT EDIT BY HAND.",
        "// Regenerate after changing a VP_/K1_/AP_/SILENCE_/NOISE_ parameter in globals.h.",
        "// tests/test_tunables_registry.py fails if this file drifts from globals.h.",
        "//",
        "// Only parameters appear here. A symbol the pipeline ASSIGNS is runtime STATE and",
        "// is excluded — exposing a writer for it would be a control that does nothing.",
        "#pragma once",
        "",
        f"#define K1_TUNABLE_COUNT {len(rows)}",
        "",
        "inline const K1Tunable K1_TUNABLES[K1_TUNABLE_COUNT] = {",
    ]
    for name, ttype, doc in rows:
        lines.append(f'  {{ "{name}", {ttype}, (void*)&{name}, "{doc}" }},')
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    rows, skipped = collect()
    text = render(rows)
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("k1_tunables_generated.h is OUT OF DATE — run scripts/tools/gen_tunables.py")
            sys.exit(1)
        print(f"tunable registry up to date ({len(rows)} parameters)")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(rows)} tunable parameters")
    print(f"excluded {len(skipped)} assigned-at-runtime symbols (state, not parameters)")
    for s in skipped[:12]:
        print(f"   state: {s}")


if __name__ == "__main__":
    main()
