// GENERATED by scripts/tools/gen_tunables.py — DO NOT EDIT BY HAND.
// Regenerate after changing a VP_/K1_/AP_/SILENCE_/NOISE_ parameter in globals.h.
// tests/test_tunables_registry.py fails if this file drifts from globals.h.
//
// Only parameters appear here. A symbol the pipeline ASSIGNS is runtime STATE and
// is excluded — exposing a writer for it would be a control that does nothing.
#pragma once

#define K1_TUNABLE_COUNT 47

inline const K1Tunable K1_TUNABLES[K1_TUNABLE_COUNT] = {
  { "AP_STREAM_ENABLED", K1_TUNE_BOOL, (void*)&AP_STREAM_ENABLED, "" },
  { "BLE_STREAM_ENABLED", K1_TUNE_BOOL, (void*)&BLE_STREAM_ENABLED, "gate for 1 Hz [ble_remoted] counters + heap telemetry (bench BLE build); toggle via :..." },
  { "K1_SILENCE_JOINT_LEVEL_SSL_FRAC", K1_TUNE_F32, (void*)&K1_SILENCE_JOINT_LEVEL_SSL_FRAC, "peakiness may only break silence at/above SSL x this" },
  { "K1_SILENCE_PEAKINESS_BREAK", K1_TUNE_F32, (void*)&K1_SILENCE_PEAKINESS_BREAK, "above this → structured audio, never silence" },
  { "K1_SILENCE_RMS_ENTER", K1_TUNE_F32, (void*)&K1_SILENCE_RMS_ENTER, "raw RMS below this → silence candidate (enter). Bench-calibrated 2026-07-10: quiet-ro..." },
  { "K1_SILENCE_RMS_EXIT", K1_TUNE_F32, (void*)&K1_SILENCE_RMS_EXIT, "raw RMS above this → not silent (Schmitt exit; > enter)" },
  { "LED_FPS", K1_TUNE_F32, (void*)&LED_FPS, "" },
  { "SECONDARY_AUTO_COLOR_SHIFT", K1_TUNE_BOOL, (void*)&SECONDARY_AUTO_COLOR_SHIFT, "" },
  { "SECONDARY_BASE_COAT", K1_TUNE_BOOL, (void*)&SECONDARY_BASE_COAT, "" },
  { "SECONDARY_BASE_COAT_INTENSITY", K1_TUNE_F32, (void*)&SECONDARY_BASE_COAT_INTENSITY, "NEW: Secondary Base coat intensity control" },
  { "SECONDARY_CHROMA", K1_TUNE_F32, (void*)&SECONDARY_CHROMA, "" },
  { "SECONDARY_LIGHTSHOW_MODE", K1_TUNE_U8, (void*)&SECONDARY_LIGHTSHOW_MODE, "1401 dual-tempo setup (2026-06-04): secondary boots on mode 18" },
  { "SECONDARY_MIRROR_ENABLED", K1_TUNE_BOOL, (void*)&SECONDARY_MIRROR_ENABLED, "" },
  { "SECONDARY_MOOD", K1_TUNE_F32, (void*)&SECONDARY_MOOD, "" },
  { "SECONDARY_PALETTE_INDEX", K1_TUNE_U8, (void*)&SECONDARY_PALETTE_INDEX, "boot palette lock (2026-08-05): K1_Naberius_Gold_gp" },
  { "SECONDARY_PALETTE_MODE_ENABLED", K1_TUNE_BOOL, (void*)&SECONDARY_PALETTE_MODE_ENABLED, "boot palette lock (2026-08-05): palette mode ON" },
  { "SECONDARY_PRISM_COUNT", K1_TUNE_F32, (void*)&SECONDARY_PRISM_COUNT, "" },
  { "SECONDARY_REVERSE_ORDER", K1_TUNE_BOOL, (void*)&SECONDARY_REVERSE_ORDER, "" },
  { "SECONDARY_SATURATION", K1_TUNE_F32, (void*)&SECONDARY_SATURATION, "" },
  { "SILENCE_DWELL_MS", K1_TUNE_U32, (void*)&SILENCE_DWELL_MS, "continuous quiet (ms) before the plate darkens" },
  { "SILENCE_ENTER_SSL_FRAC", K1_TUNE_F32, (void*)&SILENCE_ENTER_SSL_FRAC, "enter silence below this * SSL (smoothed peak)" },
  { "SILENCE_EXIT_SSL_FRAC", K1_TUNE_F32, (void*)&SILENCE_EXIT_SSL_FRAC, "leave silence above this * SSL (Schmitt gap: exit > enter)" },
  { "SILENT_FADE_DOWN_ALPHA", K1_TUNE_F32, (void*)&SILENT_FADE_DOWN_ALPHA, "slow fade to black (~1-2 s)" },
  { "SILENT_FADE_UP_ALPHA", K1_TUNE_F32, (void*)&SILENT_FADE_UP_ALPHA, "near-instant wake on first sound" },
  { "SYSTEM_FPS", K1_TUNE_F32, (void*)&SYSTEM_FPS, "" },
  { "VP_BLOOM_ALPHA", K1_TUNE_F32, (void*)&VP_BLOOM_ALPHA, "" },
  { "VP_BLOOM_FORCE_SATURATION", K1_TUNE_BOOL, (void*)&VP_BLOOM_FORCE_SATURATION, "" },
  { "VP_BLOOM_SHIFT_SCALE", K1_TUNE_F32, (void*)&VP_BLOOM_SHIFT_SCALE, "" },
  { "VP_FIX_AGC_SOFT_KNEE", K1_TUNE_BOOL, (void*)&VP_FIX_AGC_SOFT_KNEE, "" },
  { "VP_FIX_BLOOM_DECAY", K1_TUNE_BOOL, (void*)&VP_FIX_BLOOM_DECAY, "" },
  { "VP_FIX_CHROMAGRAM_SPARSENESS", K1_TUNE_BOOL, (void*)&VP_FIX_CHROMAGRAM_SPARSENESS, "" },
  { "VP_FIX_HSV_SOURCE_SAT", K1_TUNE_BOOL, (void*)&VP_FIX_HSV_SOURCE_SAT, "" },
  { "VP_FIX_PRISM_DEFAULT_OFF", K1_TUNE_BOOL, (void*)&VP_FIX_PRISM_DEFAULT_OFF, "" },
  { "VP_FIX_SECONDARY_CLEAN", K1_TUNE_BOOL, (void*)&VP_FIX_SECONDARY_CLEAN, "" },
  { "VP_PROFILE", K1_TUNE_U8, (void*)&VP_PROFILE, "" },
  { "VP_STREAM_ENABLED", K1_TUNE_BOOL, (void*)&VP_STREAM_ENABLED, "" },
  { "VP_VIVID_BLACK_LEVEL", K1_TUNE_F32, (void*)&VP_VIVID_BLACK_LEVEL, "" },
  { "VP_VIVID_CHROMA_LEVEL", K1_TUNE_F32, (void*)&VP_VIVID_CHROMA_LEVEL, "" },
  { "VP_VIVID_PRECOMP", K1_TUNE_BOOL, (void*)&VP_VIVID_PRECOMP, "" },
  { "VP_WAVEFORM_ACTIVE_FADE_REDUCTION", K1_TUNE_F32, (void*)&VP_WAVEFORM_ACTIVE_FADE_REDUCTION, "" },
  { "VP_WAVEFORM_CHROMA_BLEND_GAIN", K1_TUNE_F32, (void*)&VP_WAVEFORM_CHROMA_BLEND_GAIN, "" },
  { "VP_WAVEFORM_FALLBACK_BRIGHTNESS", K1_TUNE_F32, (void*)&VP_WAVEFORM_FALLBACK_BRIGHTNESS, "" },
  { "VP_WAVEFORM_IDLE_FADE", K1_TUNE_F32, (void*)&VP_WAVEFORM_IDLE_FADE, "" },
  { "VP_WAVEFORM_REACTIVE_PEAK_FLOOR", K1_TUNE_F32, (void*)&VP_WAVEFORM_REACTIVE_PEAK_FLOOR, "" },
  { "VP_WAVEFORM_REACTIVE_RAW_MARGIN", K1_TUNE_F32, (void*)&VP_WAVEFORM_REACTIVE_RAW_MARGIN, "" },
  { "VP_WAVEFORM_SHIFT_RATE", K1_TUNE_F32, (void*)&VP_WAVEFORM_SHIFT_RATE, "" },
  { "VP_WAVEFORM_VU_FLOOR", K1_TUNE_F32, (void*)&VP_WAVEFORM_VU_FLOOR, "" },
};
