#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026 SpectraSynq
"""Generate the firmware BLE-MIDI map header from the committed K1 map JSON."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = next(p for p in Path(__file__).resolve().parents if (p / "SPECTRASYNQ_K1_FIRMWARE").is_dir())
DEFAULT_JSON = ROOT / "docs" / "protocol" / "k1-ble-midi-map.json"
DEFAULT_OUT = ROOT / "SPECTRASYNQ_K1_FIRMWARE" / "network" / "k1_ble_midi_map.h"

K1_SYMBOLS = {"float(NUM_FREQS)": 80.0, "NUM_FREQS": 80.0}

TYPE_ENUM = {
    ("pc", "mode"): "K1MIDI_PC",
    ("cc14", "float"): "K1MIDI_CC14",
    ("cc7", "bool"): "K1MIDI_CC7_BOOL",
    ("cc7", "enum"): "K1MIDI_CC7_ENUM",
    ("nrpn", "text"): "K1MIDI_NRPN",
}


def resolve_bound(value):
    if isinstance(value, (int, float)):
        return float(value)
    if value in K1_SYMBOLS:
        return K1_SYMBOLS[value]
    raise ValueError(f"unresolved symbolic bound {value!r}")


def render(contract: dict) -> str:
    rows: list[str] = []
    text_values: list[str] = []
    for entry in contract["entries"]:
        tag = TYPE_ENUM[(entry["midi"], entry["type"])]
        cc_msb = entry.get("cc_msb", entry.get("cc", 0))
        cc_lsb = entry.get("cc_lsb", 0)
        nrpn = entry.get("nrpn_param", 0)
        vmin = resolve_bound(entry["min"]) if entry["type"] == "float" else 0.0
        vmax = resolve_bound(entry["max"]) if entry["type"] == "float" else 0.0
        text_index = len(text_values)
        values = entry.get("text_values", [])
        text_values.extend(values)
        flags: list[str] = []
        if entry.get("command"):
            flags.append("K1MIDI_FLAG_COMMAND")
        if entry.get("protected_apply"):
            flags.append("K1MIDI_FLAG_PROTECTED_APPLY")
        flag_expr = " | ".join(flags) if flags else "0"
        rows.append(
            f'  {{ "{entry["path"]}", {entry["channel"]}, {tag}, '
            f"{cc_msb}, {cc_lsb}, {nrpn}, {vmin!r}f, {vmax!r}f, "
            f"{text_index}, {len(values)}, {flag_expr} }},"
        )

    text_rows = "\n".join(f'  "{value}",' for value in text_values)
    return f"""// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 SpectraSynq
// AUTO-GENERATED by scripts/ble_midi/gen_k1_ble_midi_header.py -- DO NOT EDIT.
// Source map: docs/protocol/k1-ble-midi-map.json (registry {contract['registry_version']}, md5 {contract['registry_md5']})
#pragma once

#include <stdint.h>

#define K1_BLE_MIDI_CONTROL_COUNT {len(contract['entries'])}
#define K1_BLE_MIDI_TEXT_VALUE_COUNT {len(text_values)}
#define K1_BLE_MIDI_REGISTRY_MD5 "{contract['registry_md5']}"

typedef enum {{
  K1MIDI_PC = 0,
  K1MIDI_CC14,
  K1MIDI_CC7_BOOL,
  K1MIDI_CC7_ENUM,
  K1MIDI_NRPN,
}} K1MidiType;

typedef enum {{
  K1MIDI_FLAG_COMMAND = 1 << 0,
  K1MIDI_FLAG_PROTECTED_APPLY = 1 << 1,
}} K1MidiFlags;

typedef struct {{
  const char* path;
  uint8_t channel;
  uint8_t type;
  uint8_t cc_msb;
  uint8_t cc_lsb;
  uint16_t nrpn_param;
  float vmin;
  float vmax;
  uint8_t text_index;
  uint8_t text_count;
  uint8_t flags;
}} K1BleMidiEntry;

static const K1BleMidiEntry kK1BleMidiMap[K1_BLE_MIDI_CONTROL_COUNT] = {{
{chr(10).join(rows)}
}};

static const char* const kK1BleMidiTextValues[K1_BLE_MIDI_TEXT_VALUE_COUNT] = {{
{text_rows}
}};
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    contract = json.loads(args.json.read_text(encoding="utf-8"))
    text = render(contract)
    args.out.write_text(text, encoding="utf-8")
    try:
        out_label = args.out.relative_to(ROOT)
    except ValueError:
        out_label = args.out
    print(
        f"wrote {out_label} "
        f"({contract['control_count']} controls, header_sha256={hashlib.sha256(text.encode()).hexdigest()[:12]}...)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
