#!/usr/bin/env python3
"""deck_ui_assets.py — Operator UI asset emitter from K1 firmware truth.

Outputs:
  include/deck_palette_stops.h — FastLED knot stops from Palettes.cpp,
    ordered by gGradientPalettes[] in Palettes.h.
  include/deck_names.h — mode names from system.h set_mode_name(),
    palette display names derived mechanically from paletteNames[] in
    Palettes.h (strip _gp / K1_ prefix, underscore→space, UPPER).
    Enabled mask mirrors light_mode_is_enabled() in config_types.h.

Usage:
  python3 tools/deck_ui_assets.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def parse_palette_order(pal_h: str) -> list[str]:
    m = re.search(r"gGradientPalettes\[\]\s*=\s*\{([^}]+)\}", pal_h, re.S)
    if not m:
        raise SystemExit("gGradientPalettes[] not found in Palettes.h")
    order: list[str] = []
    for line in m.group(1).splitlines():
        s = line.strip().rstrip(",")
        if not s or s.startswith("//"):
            continue
        order.append(re.split(r"\s+", s)[0])
    return order


def parse_palette_names(pal_h: str) -> list[str]:
    m = re.search(r"paletteNames\[\]\s*PROGMEM\s*=\s*\{([^}]+)\}", pal_h, re.S)
    if not m:
        raise SystemExit("paletteNames[] not found in Palettes.h")
    names: list[str] = []
    for raw in re.findall(r'"([^"]*)"', m.group(1)):
        names.append(raw)
    return names


def parse_palette_blocks(pal_cpp: str) -> dict[str, list[tuple[int, int, int, int]]]:
    blocks: dict[str, list[tuple[int, int, int, int]]] = {}
    for m in re.finditer(r"DEFINE_GRADIENT_PALETTE\((\w+)\)\s*\{([^}]+)\}", pal_cpp):
        name = m.group(1)
        nums = [int(x) for x in re.findall(r"\d+", m.group(2))]
        if len(nums) % 4 != 0:
            raise SystemExit(f"bad stop count for {name}")
        stops = [tuple(nums[i : i + 4]) for i in range(0, len(nums), 4)]
        blocks[name] = stops  # type: ignore[assignment]
    return blocks


def parse_mode_names(system_h: str) -> list[tuple[int, str]]:
    """Extract set_mode_name(index, \"NAME\") pairs in declaration order."""
    pairs: list[tuple[int, str]] = []
    for m in re.finditer(
        r'set_mode_name\s*\(\s*(\d+)\s*,\s*"([^"]*)"\s*\)', system_h
    ):
        pairs.append((int(m.group(1)), m.group(2)))
    if not pairs:
        raise SystemExit("set_mode_name() not found in system.h")
    return pairs


def parse_disabled_modes(config_types: str) -> set[int]:
    """Parse light_mode_is_enabled() cases that return false."""
    m = re.search(
        r"inline bool light_mode_is_enabled\(uint8_t mode\)\s*\{(.*?)^\s*\}",
        config_types,
        re.S | re.M,
    )
    if not m:
        raise SystemExit("light_mode_is_enabled() not found in config_types.h")
    body = m.group(1)
    # Collect LIGHT_MODE_* identifiers in the false-return switch cases.
    disabled_syms = re.findall(r"case\s+(LIGHT_MODE_\w+)\s*:", body)
    # Map enum ordinals from enum lightshow_modes.
    enum_m = re.search(r"enum lightshow_modes\s*\{(.*?)\n\s*NUM_MODES", config_types, re.S)
    if not enum_m:
        raise SystemExit("enum lightshow_modes not found")
    ordinals: dict[str, int] = {}
    idx = 0
    for line in enum_m.group(1).splitlines():
        s = line.strip()
        if not s or s.startswith("//"):
            continue
        # LIGHT_MODE_FOO,  or LIGHT_MODE_FOO = N,
        tok = s.split(",")[0].strip()
        if not tok.startswith("LIGHT_MODE_"):
            continue
        name = tok.split("=")[0].strip()
        if "=" in tok:
            idx = int(tok.split("=")[1].strip())
        ordinals[name] = idx
        idx += 1
    disabled: set[int] = set()
    for sym in disabled_syms:
        if sym not in ordinals:
            raise SystemExit(f"disabled symbol {sym} missing from enum")
        disabled.add(ordinals[sym])
    return disabled


def palette_display_name(ident: str) -> str:
    """Mechanical condensation of firmware identifier — never invent synonyms."""
    s = ident
    if s.endswith("_gp"):
        s = s[:-3]
    if s.startswith("K1_"):
        s = s[3:]
    s = s.replace("_", " ")
    return s.upper()


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_stops_h(order: list[str], blocks: dict, out_path: Path) -> None:
    lines: list[str] = [
        "#pragma once",
        "/* Auto-generated by tools/deck_ui_assets.py from K1 Palettes.cpp — do not edit. */",
        "#include <stdint.h>",
        f"#define DECK_PALETTE_STOP_TABLE_COUNT {len(order)}",
        "typedef struct { uint8_t index; uint8_t r; uint8_t g; uint8_t b; } DeckPaletteStop;",
        "typedef struct { const DeckPaletteStop* stops; uint8_t count; } DeckPaletteStrip;",
        "",
    ]
    for i, name in enumerate(order):
        stops = blocks[name]
        lines.append(f"static const DeckPaletteStop kDeckPalStops_{i:02d}[] = {{ /* {name} */")
        for idx, r, g, b in stops:
            lines.append(f"  {{{idx}, {r}, {g}, {b}}},")
        lines.append("};")
    lines.append("")
    lines.append("static const DeckPaletteStrip kDeckPaletteStrips[DECK_PALETTE_STOP_TABLE_COUNT] = {")
    for i, name in enumerate(order):
        lines.append(
            f"  {{kDeckPalStops_{i:02d}, "
            f"(uint8_t)(sizeof(kDeckPalStops_{i:02d})/sizeof(kDeckPalStops_{i:02d}[0]))}}, "
            f"/* {i:02d} {name} */"
        )
    lines.append("};")
    lines.append("")
    lines.append("static inline const DeckPaletteStrip* deck_palette_strip(uint8_t index) {")
    lines.append("  if (index >= DECK_PALETTE_STOP_TABLE_COUNT) return &kDeckPaletteStrips[0];")
    lines.append("  return &kDeckPaletteStrips[index];")
    lines.append("}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")


def emit_names_h(
    mode_pairs: list[tuple[int, str]],
    disabled: set[int],
    palette_idents: list[str],
    out_path: Path,
) -> None:
    max_mode = max(i for i, _ in mode_pairs)
    mode_count = max_mode + 1
    by_idx = {i: n for i, n in mode_pairs}
    missing = [i for i in range(mode_count) if i not in by_idx]
    if missing:
        raise SystemExit(f"missing set_mode_name indices: {missing}")

    lines: list[str] = [
        "#pragma once",
        "/* Auto-generated by tools/deck_ui_assets.py — do not edit.",
        " * Modes  : SPECTRASYNQ_K1_FIRMWARE/system/system.h set_mode_name()",
        " * Enabled: SPECTRASYNQ_K1_FIRMWARE/system/config_types.h light_mode_is_enabled()",
        " * Palettes: SPECTRASYNQ_K1_FIRMWARE/visual/Palettes.h paletteNames[]",
        " * Display names = mechanical transform of firmware identifiers (no invented synonyms).",
        " */",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        f"#define DECK_MODE_COUNT              {mode_count}",
        f"#define DECK_MODE_COUNT_CURATED      DECK_MODE_COUNT  /* legacy alias */",
        f"#define DECK_PALETTE_COUNT           {len(palette_idents)}",
        "",
        f"static const char* const kDeckModeNames[DECK_MODE_COUNT] = {{",
    ]
    for i in range(mode_count):
        lines.append(f'  "{c_escape(by_idx[i])}",  /* {i:02d} */')
    lines.append("};")
    lines.append("")
    lines.append("/* 1 = selectable (mirrors light_mode_is_enabled). */")
    lines.append(f"static const uint8_t kDeckModeEnabled[DECK_MODE_COUNT] = {{")
    en_vals = [0 if i in disabled else 1 for i in range(mode_count)]
    for row in range(0, mode_count, 11):
        chunk = en_vals[row : row + 11]
        lines.append("  " + ", ".join(str(v) for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("/* Firmware paletteNames[] identifiers (source of truth). */")
    lines.append(f"static const char* const kDeckPaletteIdents[DECK_PALETTE_COUNT] = {{")
    for i, ident in enumerate(palette_idents):
        lines.append(f'  "{c_escape(ident)}",  /* {i:02d} */')
    lines.append("};")
    lines.append("")
    lines.append("/* UI display strings derived from identifiers (strip _gp/K1_, UPPER). */")
    lines.append(f"static const char* const kDeckPaletteNames[DECK_PALETTE_COUNT] = {{")
    for i, ident in enumerate(palette_idents):
        disp = palette_display_name(ident)
        lines.append(f'  "{c_escape(disp)}",  /* {i:02d} ← {ident} */')
    lines.append("};")
    lines.append("")
    lines.append("static inline const char* deck_mode_name(uint8_t index)")
    lines.append("{")
    lines.append("  if (index < DECK_MODE_COUNT) return kDeckModeNames[index];")
    lines.append('  return "MODE";')
    lines.append("}")
    lines.append("")
    lines.append("static inline bool deck_mode_is_enabled(uint8_t index)")
    lines.append("{")
    lines.append("  if (index >= DECK_MODE_COUNT) return false;")
    lines.append("  return kDeckModeEnabled[index] != 0;")
    lines.append("}")
    lines.append("")
    lines.append("static inline const char* deck_palette_name(uint8_t index)")
    lines.append("{")
    lines.append("  if (index < DECK_PALETTE_COUNT) return kDeckPaletteNames[index];")
    lines.append('  return "PALETTE";')
    lines.append("}")
    lines.append("")
    lines.append("static inline const char* deck_palette_ident(uint8_t index)")
    lines.append("{")
    lines.append("  if (index < DECK_PALETTE_COUNT) return kDeckPaletteIdents[index];")
    lines.append('  return "";')
    lines.append("}")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    p = argparse.ArgumentParser(description="Operator UI asset emitter")
    p.add_argument("--out-stops", default="", help="palette stops header path")
    p.add_argument("--out-names", default="", help="names header path")
    p.add_argument(
        "--out",
        default="",
        help="legacy alias for --out-stops",
    )
    p.add_argument(
        "--emit-placeholder",
        action="store_true",
        help="legacy flag — ignored",
    )
    args = p.parse_args()

    root = repo_root()
    pal_h = (root / "SPECTRASYNQ_K1_FIRMWARE/visual/Palettes.h").read_text()
    pal_cpp = (root / "SPECTRASYNQ_K1_FIRMWARE/visual/Palettes.cpp").read_text()
    system_h = (root / "SPECTRASYNQ_K1_FIRMWARE/system/system.h").read_text()
    config_types = (root / "SPECTRASYNQ_K1_FIRMWARE/system/config_types.h").read_text()

    order = parse_palette_order(pal_h)
    idents = parse_palette_names(pal_h)
    if len(order) != len(idents):
        raise SystemExit(
            f"gGradientPalettes ({len(order)}) vs paletteNames ({len(idents)}) length mismatch"
        )
    for i, (a, b) in enumerate(zip(order, idents)):
        if a != b:
            raise SystemExit(f"index {i}: order={a} name={b} mismatch")

    blocks = parse_palette_blocks(pal_cpp)
    missing = [n for n in order if n not in blocks]
    if missing:
        print("missing palette definitions:", missing, file=sys.stderr)
        return 1

    mode_pairs = parse_mode_names(system_h)
    disabled = parse_disabled_modes(config_types)

    stops_out = Path(args.out_stops or args.out) if (args.out_stops or args.out) else (
        root / "tab5_firmware/include/deck_palette_stops.h"
    )
    if not stops_out.is_absolute():
        stops_out = (Path.cwd() / stops_out).resolve()
    names_out = Path(args.out_names) if args.out_names else (
        root / "tab5_firmware/include/deck_names.h"
    )
    if not names_out.is_absolute():
        names_out = (Path.cwd() / names_out).resolve()

    emit_stops_h(order, blocks, stops_out)
    emit_names_h(mode_pairs, disabled, idents, names_out)

    print(f"deck_ui_assets.py: wrote {stops_out}")
    print(f"deck_ui_assets.py: wrote {names_out}")
    print(f"  modes={len(mode_pairs)} disabled={sorted(disabled)}")
    print(f"  palettes={len(order)}")
    print(f"  index 07 = {order[7]} → {palette_display_name(idents[7])}")
    print(f"  index 40 = {order[40]} → {palette_display_name(idents[40])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
